### ISSUE TITLE
AttributeError: 'tuple' object has no attribute 'state_dict'

### ISSUE THREAD

**Issue by 1228483536** [vidit09/domaingen#11]
Hello, when I running your code, it has errors following. What should I do?
Traceback (most recent call last):
  File "/mnt/workspace/domaingen-main/train.py", line 601, in <module>
    main(args)
  File "/mnt/workspace/domaingen-main/train.py", line 593, in main
    trainer.train()
  File "/mnt/workspace/detection/detect/detectron2/engine/defaults.py", line 486, in train
    super().train(self.start_iter, self.max_iter)
  File "/mnt/workspace/detection/detect/detectron2/engine/train_loop.py", line 156, in train
    self.after_step()
  File "/mnt/workspace/detection/detect/detectron2/engine/train_loop.py", line 190, in after_step
    h.after_step()
  File "/mnt/workspace/detection/detect/detectron2/engine/hooks.py", line 299, in after_step
    self._best_checking()
  File "/mnt/workspace/detection/detect/detectron2/engine/hooks.py", line 272, in _best_checking
    self._checkpointer.save(f"{self._file_prefix}", **additional_state)
  File "/opt/conda/envs/domain/lib/python3.9/site-packages/fvcore/common/checkpoint.py", line 118, in save
    data[key] = obj.state_dict()
  File "/mnt/workspace/domaingen-main/train.py", line 430, in state_dict
    ret = super().state_dict()
  File "/mnt/workspace/detection/detect/detectron2/engine/defaults.py", line 500, in state_dict
    ret["_trainer"] = self._trainer.state_dict()
  File "/mnt/workspace/detection/detect/detectron2/engine/train_loop.py", line 425, in state_dict
    ret["optimizer"] = self.optimizer.state_dict()
AttributeError: 'tuple' object has no attribute 'state_dict'

**Comment by vidit09** [comment]
Hello ,

Please try this [solution](https://github.com/vidit09/domaingen/issues/3#issuecomment-1837803303)

**Comment by 1228483536** [comment]
Oh,thanks,I will try it.
